### ISSUE TITLE
How to activate a virtual enviromment?

### ISSUE THREAD

**Issue by hello-code** [proofit404/pyenv-mode#10]
I'm using pyvenv-mode,that use pyvenv-activate activate virtual enviromment;
I don't know how to activate a virtual enviromment in pyenv-mode ?
What is different with pyvenv-mode?
Thanks!

**Comment by proofit404** [comment]
To use `pyenv-mode` you need [pyenv](https://github.com/yyuu/pyenv) and [pyenv-virtualenv](https://github.com/yyuu/pyenv-virtualenv). Create virtual environment with
```shell
pyenv virtualenv 3.4.1 myenv
```
and activate it with
```
M-x pyenv-mode-set RET myenv RET
```
Hope this help.

**Comment by hello-code** [comment]
Thanks!

**Comment by proofit404** [comment]
I think we can close this issue.
