### ISSUE TITLE
Is this library Jedi-compatible?

### ISSUE THREAD

**Issue by nayefc** [proofit404/pyenv-mode#11]
I tried using it and it seems like it works but I am not sure if it is correct or if it will mess up anything for me in the future.

**Comment by proofit404** [comment]
Hi, Nayef!

If you plan to use pyenv-mode together with [emacs-jedi][https://github.com/tkf/emacs-jedi] project there are follwing options for you:
* don't use `jedi-install-server` command, activate interesting python environment, install `jediepcserver` dependencies manualy into that env and start the server
* add current environment to the `jedi-server-args` (see doc for more help)
* same as first item but install dependencies locally in the dirrectory containing `jediepcserver.py` file so you don't need to reinstall dependencies into each environment
* try to use anaconda-mode, it make virtualenv usage as simple as `inf-python` does

**Comment by nayefc** [comment]
Thanks for the quick response!

So for the first option, does that mean just activate pyenv normally and open the document and not use `jedi-install-server`? I've been doing that and its working! Haven't tried installing/uninstalling anything though.

Would Jedi use pyenv's active environment out of the box? Or am I just lucky?

If not, I guess the second option is the most feasible for me. However, I'd need to add all my virtualenvs manually. Correct?

**Comment by proofit404** [comment]
`jediepcserver.py` has few dependencies: `jedi`, `epc` and `sexpdata`.  To make this server work you need to install this dependencies and make they available for python you use.  `jedi.el` dosn't restart its server when python environment changes. May you has older running server.

Jediepcserver will use pyenv python only if you activate you env before starting the server and you don't run `jedi-install-server` before.

If you will choose second option I recomend sepecify only one env at time and restart server manually after you switch environment in that way. If you add each environment at one you'll get completions for libraries doesn't used in current project.

**Comment by proofit404** [comment]
If I answer all your questions please close this issue.

**Comment by nayefc** [comment]
What do you mean "only if you activate your env before starting the server and you don't run `jedi-install-server`? What is the server here? Isn't it `jedi-install-server`? If so, how do I start the server without running that command?

If by server you mean just enable jedi-mode, then yes, I do activate pyenv before I open my python files. Does that explain why Jedi is working for pyenv for me right now?

Which approach do you recommend? From the first option you just describe, I understand that if I install these certain dependencies in my virtualenv, then I can get Jedi to work on pyenv as soon as its activated without having to do anything in order or restarting anything at all? Is this correct?

Sorry for my confusion.

**Comment by proofit404** [comment]
By activate I mean `pyenv-mode-set` command.  After that every command runs `python` executable will use one from selected environment. Except those who specify absolute path to the python executable like [jedi:start-server](https://github.com/tkf/emacs-jedi/blob/master/jedi.el#L529).

Server here is tiny python subprocess used to interact with jedi library from emacs. `jedi-install-server` setup special virtual environment for this server into `~/.emacs.d/.python-environments/default`. Remove this directory if it present. Install jedi server dependencies into your virtual environment.

If you start emacs no jedi server process until you open any python file. So set your environment before open any python file. After that all must just work. But only for this virtualenv.

As for me I wrote `anaconda-mode` because `emacs-jedi` and `elpy` packages are so tricky to use.

**Comment by nayefc** [comment]
Yes, I am doing the latter.

Is `anaconda-mode` as good as Jedi? Does it have the same popup/tooltip and everything?

**Comment by proofit404** [comment]
Maybe you can provide me some screenshot with popup/tooltip and everything so I can answer your question more detailed. If you miss some functionality I think it is easy to implement.

**Comment by nayefc** [comment]
I'll give it a shot and try it myself. I'm having a hard time unbinding Jedi keybindings anyway so could be a good thing! It overrides C-c d and C-c , and C-c . for me which I need and I can't figure out how to unbind them. Thanks for your help!

**Comment by proofit404** [comment]
Also note that there are `ac-anaconda` for integration with `auto-complete-mode` and `company-anaconda` for integration with `company-mode`.

**Comment by proofit404** [comment]
For freeing you favorite keybindings try following elisp snippet:
```lisp
(eval-after-load "jedi"
 '(progn
   (define-key jedi-mode-map (kdb "C-c d") nil)
   (define-key jedi-mode-map (kdb "C-c .") nil)
   (define-key jedi-mode-map (kdb "C-c ,") nil)))
```

**Comment by nayefc** [comment]
Oh, I was doing `(eval-after-load 'jedi-mode`. Yours worked.

Thanks a lot!

**Comment by proofit404** [comment]
You're welcome :D
