### ISSUE TITLE
Rename of `python-shell-virtualenv-path`

### ISSUE THREAD

**Issue by marsam** [proofit404/pyenv-mode#12]
Hi:
From the Emacs version 25.1 the variable `python-shell-virtualenv-path` [has been renamed](https://lists.gnu.org/archive/html/emacs-diffs/2014-11/msg00196.html) to `python-shell-virtualenv-root`.

**Comment by proofit404** [comment]
Thanks for report! I think we need to use variable name depending of emacs version. Will fix this soon.

**Comment by proofit404** [comment]
Done with `pythonic` package.
