### ISSUE TITLE
New virtualenv can't be picked up by pyenv-mode

### ISSUE THREAD

**Issue by nayefc** [proofit404/pyenv-mode#13]
Hello,

I created a new virtualenv using pyenv (which does exist in ~/.pyenv/versions) but pyenv-mode in Emacs is not autocompleting it / cannot find it.

I just started using a new computer and have a fresh install of Emacs, pyenv and pyenv-mode.

Any idea what the problem could be?

Thanks.

**Comment by proofit404** [comment]
Can you do following commands?
```lisp
M-: (shell-command-to-string "pyenv root") RET
M-: (shell-command-to-string "pyenv versions --bare") RET
```
I suppose you forgot to add pyenv into system PATH.

**Comment by nayefc** [comment]
Sure. For both, I get:

```bash
/bin/bash: pyenv: command not found
```


I have installed pyenv using brew:

```bash
$ brew info pyenv
pyenv: stable 20150226 (bottled), HEAD
https://github.com/yyuu/pyenv
/usr/local/Cellar/pyenv/20150226 (330 files, 2.7M) *
```

What is wrong with my installation? Thanks!

**Comment by proofit404** [comment]
I'm not familiar with homebrew since I doesn't have mac. You can compare values of you shell `PATH` variable with your emacs `exec-path` variable. Also you can try [this](https://github.com/purcell/exec-path-from-shell) package.

**Comment by nayefc** [comment]
Figured it out, thank you.

I had that package installed using `use-package` and forgot to ensure that it must always be installed. Since it gets lazily loaded by default and it never gets explicitly called, it was never installed.

**Comment by proofit404** [comment]
Glad we solve it.

**Comment by nayefc** [comment]
@proofit404 I remember you helped me with Jedi and pyenv before. Do you use Jedi? Do you know if it requires an active virtualenv to run `install-server`?

**Comment by proofit404** [comment]
I write `anaconda-mode` because `jedi.el` is so uncomfortable to use. Maybe you can try it instead? Be careful if you install pip with homebrew.

As about `jedi.el` if I understand correct you can install argparse, jedi and epc into each of you environments and remove `jedi.el!` default virtualenv from `.emacs`.

**Comment by nayefc** [comment]
Is `anaconda-mode` as mature as Jedi? i.e: does it provide the same `autocompletion` and `jump-to-definition` without issues?

**Comment by proofit404** [comment]
Both anaconda and jedi use same library under the hood. You can use ac, company and complete-at-point frontends for in buffer completion. `M-.` works same way.

**Comment by nayefc** [comment]
I've added a custom `PYTHONPATH` in pyenv's activate script. Is there a way to have Emacs pyenv-mode pick it up?

**Comment by proofit404** [comment]
I think the easiest way to do that is `M-x setenv RET PYTHONPATH RET /your/python/path RET`. Also `anaconda-mode` well handle this transparently for you.

**Comment by nayefc** [comment]
`anaconda-mode` uses `PYTHONPATH` by default?

**Comment by proofit404** [comment]
> anaconda-mode uses PYTHONPATH by default? Doesn't look like it.
Every program running within emacs will use it, this is how subprocesses works.
> I need to use company with it to get the dropdowns
You can use what ever you like. `auto-complete`, `company` and emacs default completion frontends supported currently. `helm` maybe in the future.
> company seems super buggy. Doesn't work right out of the box properly.
`company` has brilliant code base. `auto-complete` is the "super buggy" package.
> It also needs a running python process in Emacs.
jedi.el works this way, elpy works this way, anaconda-mode works this way.  This is the only way to use foreign libraries from emacs lisp.

**Comment by nayefc** [comment]
>> anaconda-mode uses PYTHONPATH by default? Doesn't look like it.

> Every program running within emacs will use it, this is how subprocesses works.

I ran `getenv` though and `PYTHONPATH` retrieves nothing. Why isn't it showing up?

> company seems super buggy. Doesn't work right out of the box properly.

>> company has brilliant code base. auto-complete is the "super buggy" package.

Yeah seems like its only buggy on the terminal only. On GUI Emacs, it works nicely.

> It also needs a running python process in Emacs.

>> jedi.el works this way, elpy works this way, anaconda-mode works this way. This is the only way to use foreign libraries from emacs lisp.

I do not have to explicitly run python though. In Anaconda, I have to explicitly run python. That's really annoying.

**Comment by nayefc** [comment]
Everything is fine now apart from PYTHONPATH. I am doing `setenv` but that is impractical. Anyway to put it in some script that pyenv-mode picks up?

**Comment by proofit404** [comment]
`pyenv-mode` by it's nature doesn't deal with virtualenv activate scripts. The only purpose of this package is to specify what python version to use.

But you can use `(setenv "PYTHONPATH" "/path")` in your custom file for example.

**Comment by nayefc** [comment]
@proofit404 Hmm yeah that makes sense. What about `pyenv-virtualenv` though? Doesn't it use some activate script? Also, what do you mean by custom file?

Thank you!

**Comment by proofit404** [comment]
By custom file I mean your `.emacs.d`.  Usually I do following:
```bash
pyenv virtualenv venv
pyenv shell venv
```
pyenv-mode works same way. I doesn't use its activate command.

**Comment by nayefc** [comment]
Yeah I did add it to `.emacs.d` but now this applies to all Emacs sessions, even ones not dealing with Python.

`pyenv` does use the activate file. Otherwise, how will it get the virtualenv started? I've placed my `PYTHONPATH` change in the `activate` script and when I start a venv with `pyenv activate venv` or `pyenv shell venv`, `PYTHONPATH` is updated in the shell accordingly. However, that environment variable does not get picked up by Emacs. I also tried to copy it using `exec-path-from-shell` and that did not work. I guess I am going to have to live with putting it into an init file and keep going through the trouble of changing it when switching between python projects.

Is there a way to place a hook in `pyenv-virtualenv` for when a specific virtualenv is being activated?

**Comment by proofit404** [comment]
Activation scripts executed automatically when you initialize pyenv inside your shell i.e you add `eval $(pyenv init -)`.

**Comment by nayefc** [comment]
Hmm, I still get can't it to read the environment variables defined there. I will probably try to see how to get it to work using `exec-path-from-shell`. Thanks.

**Comment by nayefc** [comment]
Actually, here's my fix in `pyenv-mode`:

```lisp
 (defun pyenv-mode-set (version)                                          
   "Set python shell VERSION."                                            
   (interactive (list (pyenv-mode-read-version)))                         
   (setq python-shell-virtualenv-path (pyenv-mode-full-path version))     
   (setenv "PYENV_VERSION" version)                                       
   (if (equal version "venv")                                         
       (setenv "PYTHONPATH"                                               
               "/path/to/dir/here"))
   (force-mode-line-update))                                              
````
