### ISSUE TITLE
Starting correct version of Ipython based on mode-set python version

### ISSUE THREAD

**Issue by DGalt** [proofit404/pyenv-mode#14]
I'm not sure if this is the correct place to be asking this, so please excuse me if it is not. 

I'm on Arch linux, using Emacs 24.5.1. I have two version of python installed - the default for arch (which is python3), located at /usr/bin/python. I also have python2.7 installed globally via pacman at /usr/bin/python2

All of the python2 packages in the pacman repository are named as such. So, for example, ipython is called ipython2. 

This is causing an issue, though, when I go to start up a Python2 repl in Emacs. So, if I set, in Emacs, my pyenv-mode to my Python2 install (system-2.7.10), and then go to start a python repl (M-x run-python), I am getting a Python3 Ipython repl. 

If I remove the lines specifying Ipython in my emacs config, I get a correct Python2 repl. Also, if I change my emacs config to specify "ipython2" (see below) instead of "ipython" I get the correct Python2 repl. But then I fail to get a Python3 IPython repl if I I'm using the default ("system") pyenv-mode in Emacs. 

The lines in my emacs config that set up Ipyhon usage are: 

(setq python-shell-interpreter "ipython")
(setq-default py-which-bufname "IPython")

Is there a way to check which version of Python is currently set in pyenv-mode and subsequently call the correct version of Ipython?

**Comment by proofit404** [comment]
Hi @DGalt 
First of all this is definitely not an `pyenv-mode` issue, so I close it.
But I'd like to help you to get work setup.
If you have *any* question you think I can help just drop me email or write it right here.
I suppose you use `python.el` from standard emacs libs. If so `py-which-bufname` is unnecessary.
You can customize `python-shell-interpreter` to absolute path `/usr/bin/python` or `/usr/bin/python2`. Next time you do `run-python` will use specified python. You can run multiple python semulteniously. Customize `python-shell-buffer-name` variable for it.

**Comment by proofit404** [comment]
For this case you doesn't need `pyenv-mode` at all.

**Comment by DGalt** [comment]
I'm a bit confused, can you elaborate a bit more? If I set `python-shell-interpreter1 to `/usr/bin/python` won't `run-python` always run that version of python (in this case, python3)? Similarly, if I set it to `'usr/bin/python2` it's always going to run the python2 repl

What I'm trying to achieve is to be able to tell Emacs that I want to run a python2 ipython repl (or a python3 ipython repl). If I don't use ipython, this all works fine. I set pyenv-mode to my python2 system install, and I get a python2 repl when I use `run python`. Similarly, if I have pyenv-mode set to the python system install, I get a python 3 repl. 

The problem is that if I specify my interpreter as ipython, I only ever get a python3 shell. Maybe I'm misunderstanding what you're saying though. 

I'm using `pyenv-mode` for more than just this, though, because I'd also like to get the appropriate autocompletion suggestions / doc lookups / linting (I'm using your wonderful anaconda package as well). 

Thanks for your help, it's very much appreciate. And sorry that I put this here, I wasn't sure if I should just email you or open a question (obviously I should have done the former).

**Comment by proofit404** [comment]
You can specify absolute path for ipython executable (`/usr/bin/ipython` for python3 and `/usr/bin/ipython2` for python2). More reliable way which I personally use is setup `python-shell-interpreter` to `"python"` and `python-shell-interpreter-args` to `"-m IPython"`.

You doesn't need to edit your config file each time you need to setup some variable inside emacs. You can use `M-x customize RET` to setup python-mode customizations and save it to your `custom.el` file. You can do `M-: (setq python-shell-interpreter "/usr/bin/python") RET` to affect current emacs session globally. Next time you do `M-x run-python RET` you will get proper repl buffer. You doesn't need to affect global variables at all if you don't want to. Suppose you set python3 as your prefered python and want just run python2 buffer.
```lisp
M-: (let ((python-shell-interpreter "/usr/bin/python2")
          (python-shell-interpreter-args "-m IPython")
          (python-shell-buffer-name "*Python2*"))
      (call-interactively 'run-python)) RET
```
You can even write an interactive command in your configuration file
```lisp
(defun run-python2 ()
  (interactive)
  (let ((python-shell-interpreter "/usr/bin/python2")
        (python-shell-interpreter-args "-m IPython")
        (python-shell-buffer-name "*Python2*"))
    (call-interactively 'run-python)))
```
Than you can run python2 interpreter with `M-x run-python2 RET` command.
Hope this helps.

**Comment by DGalt** [comment]
Perfect. Setting `python-shell-interpreter` to `"python"` and `python-shell-interpreter-args` to `"-m IPython"` does exactly what I was trying to achieve. Thanks so much!

**Comment by proofit404** [comment]
You're welcome :D
