### ISSUE TITLE
Support for anaconda/miniconda environments

### ISSUE THREAD

**Issue by cpaulik** [proofit404/pyenv-mode#15]
Anaconda or miniconda environments are not listed in the `pyenv versions` command but in `pyenv virtualenvs --list`. The also must be activated using the `pyenv activate` command.

Could you add support for these kinds of environments? I could also help with the implementation if you tell me how you think the selection process should be.

See also https://github.com/yyuu/pyenv-virtualenv#anaconda-and-miniconda

**Comment by proofit404** [comment]
Thanks for info. I need some time to think of it (say a day).

**Comment by cpaulik** [comment]
So I had some time on my hands so I tried to fix this.
