### ISSUE TITLE
pyenv virtualenvs has to be installed

### ISSUE THREAD

**Issue by cpaulik** [proofit404/pyenv-mode#18]
I have introduced a bug with #16 .

When the command [pyenv virtualenv](https://github.com/yyuu/pyenv-virtualenv) is not installed then the list of environments now contains 

```
pyenv:
no
such
command
`virtualenvs'
```

I'll try to fix this when I have time unless you do it first :smile:

**Comment by proofit404** [comment]
Not notice it since I'm use `virtualenv` plugin :smile:

**Comment by proofit404** [comment]
See #22
