### ISSUE TITLE
projectile pyenv trick

### ISSUE THREAD

**Issue by aiguofer** [proofit404/pyenv-mode#19]
I love the trick for automatically activating the right pyenv with projectile, however most of my projects are not python, so they don't have a pyenv version associated. I was wondering if you guys could help me with the lisp to look at the contents of ~/.pyenv/version if it doesn't find a pyenv version with the same name as the project?

Thanks!

**Comment by proofit404** [comment]
Does following snippet works for you?
```lisp
(defun projectile-pyenv-mode-set ()
  (let ((project (projectile-project-name)))
    (when (member project (pyenv-mode-versions))
      (pyenv-mode-set project))))
```

**Comment by aiguofer** [comment]
`member: Symbol's function definition is void: pyenv-mode-versions`

I've got version 20150929.1352 installed if that helps.

**Comment by aiguofer** [comment]
Interestingly enough, if I do `pyenv-mode-set`, helm shows me the possible pyenv versions that I have installed.

**Comment by proofit404** [comment]
Try to add `(require 'pyenv-mode)` into your configuration file.

**Comment by aiguofer** [comment]
still nothing... that's really weird, I see the function definition in pyenv-mode.el.. does the missing `;;;###autoload` decorator have anything to do with it?

**Comment by proofit404** [comment]
It shouldn't be autoloaded since it isn't implied to be used directly.

**Comment by aiguofer** [comment]
Hmm I'm not sure what else I did but I finally got it working... it does `(require 'pyenv-mode)` then defines the function, then adds the hook.

Thanks! might be worth adding this to the README

**Comment by proofit404** [comment]
I have update this snippet in the README.
