### ISSUE TITLE
Projectile: switching to local, not same-name, env

### ISSUE THREAD

**Issue by lvh** [proofit404/pyenv-mode#20]
I think that projectile integration should use the pyenv environment for the project path instead of an environment with the same name.

First off, this is how pyenv is "supposed" to work (a global env with local, path-based override). If a new project (for example, for a talk that incidentally has some Python source) doesn't have its own local pyenv, but the default (global) env has the appropriate packages, it will magically work. Furthermore, right now, if a project has a local pyenv but it doesn't have the same name as the project, pyenv-mode breaks but pyenv (from a terminal) works fine.

This is particularly useful for the flycheck integartion that pyenv-mode provides: all the necessary flycheck checkers may be in the default env, but installing them for every little project (some of which, as I mentioned, like talks, only have < 10 lines of Python) is kind of annoying when there's a default env available.

**Comment by proofit404** [comment]
Hello.

Projectile code snippet is optional.  That why it isn't included into
`pyenv-mode` sources.  It based on assumption that user will name
project virtual environment same as project itself.  This allow to
avoid hitting `C-c C-s` each time you switch the project.

I agree with you that global/local version behavior set by
`.python-version` files is the native way to use `pyenv` tool.  You
doesn't need to use `pyenv-mode` at all if you happy with it.

The purpose of `pyenv-mode` is provide `pyenv shell <version>`-like
behavior for emacs.  I use it to activate environments created with
`pyenv virtualenv` command and simultaneously project
`.python-version` specifies interpreter version to use for virtual
environment creation.  It contains multiple version for projects
tested with `tox`.  To use your global or local python version just
unset Emacs override with `C-c C-u`.

If you install code checkers into global environment and
setup local version for directory without installed checkers you can't
use those ones from shell too.

I doesn't see any issue with `pyenv-mode` itself.  But I can improve
projectile code snippet any time if you describe sophisticated
behavior.

**Comment by lvh** [comment]
Oops! I mistakenly believed that my global env had the appropriate pyflakes env in it. My bad, thanks for your reply.

**Comment by proofit404** [comment]
You're welcome :smile:
