### ISSUE TITLE
Does not set `exec-path` correctly in anaconda virtualenv

### ISSUE THREAD

**Issue by cpaulik** [proofit404/pyenv-mode#21]
Using `pyenv-activate` in the shell on a anaconda environment modifies my path to include e.g.

```
PATH=/home/cpa/.pyenv/versions/miniconda-3.16.0/envs/pytesmo/bin:/home/cpa/.pyenv/shims:
```

Activation of the same environment in emacs does not add the same path to `exec-path`

**Comment by proofit404** [comment]
I guess this package shouldn't provide `activate` functionality ([pyenv mode doesn't...](https://github.com/proofit404/pyenv-mode#pyenv-mode-doesnt)). That why pyenv-mode commands stands from set/unset and not from activate/deactivate. Maybe you can implement pyenv-anaconda-mode or similar package with full support of anaconda virtual environments? Then I can mention this package in the README and revert autocompletion with virtualenv subcommand.

What do you think?

**Comment by cpaulik** [comment]
Oh, I did not realize this section in the readme.

This might be a problem in pyenv. 

Let's wait and see what https://github.com/yyuu/pyenv/issues/467 brings.

**Comment by cpaulik** [comment]
I think this is solved since https://github.com/yyuu/pyenv-virtualenv/issues/103 and PR's within have brought some changes to `pyenv`. You should now also be able to revert to the `pyenv versions` command since it now lists all versions and environments.

**Comment by proofit404** [comment]
See #22
