### ISSUE TITLE
projectile-pyenv-mode-set is slightly buggy

### ISSUE THREAD

**Issue by amitu** [proofit404/pyenv-mode#23]
If you switch to a pyenv enabled project, it picks up and activates the right project. But then when you switch to another project that is not pyenv based, and is using system python, then the old version remains.

```elisp
(require 'pyenv-mode)

(defun projectile-pyenv-mode-set ()
  "Set pyenv version matching project name."
  (let ((project (projectile-project-name)))
    (if (member project (pyenv-mode-versions))
      (pyenv-mode-set project)
      (pyenv-mode-set "system"))))

(add-hook 'projectile-switch-project-hook 'projectile-pyenv-mode-set)
```

May be we can also guard this by (when (eq major-mode "python-mode") ... )

This would be "buggy" for those who have configured a given pyenv as part of their .zshrc etc, and would want to switch to *that* env instead of "system".

**Comment by proofit404** [comment]
Hope updated version will be useful to you.

**Comment by amitu** [comment]
This is better. Thanks.

**Comment by amitu** [comment]
I am confused now.

The 'projectile-switch-project-hook hook is not called as often I thought it would. I have two projects, and few files open from both projects. Switching between buffer of one project to another makes (projectile-find-file) show the right list of files based on project of current buffer. 

Which is what I was expecting would happen with the above hook, if I do run-python, I would get right python depending on the buffer I am in.

One solution I can think of is use buffer-list-update-hook instead. But I feel that would be too heavy, buffer switch happens often.

Why is the variable that run-python etc use to pick the path of python buffer local? 

Or am I doing something wrong?

**Comment by proofit404** [comment]
You can try to do this with buffer local variables and python-mode-hook.
