### ISSUE TITLE
Could pyenv-mode only a buffer-local mode?

### ISSUE THREAD

**Issue by Superbil** [proofit404/pyenv-mode#25]
When I enable pyenv-mode, I found that was a global minor-mode.
Some keybind has been overwrite, like C-c C-s. I use this keybind in different mode.

Could pyenv-mode change to a buffer-local mode, let only work for some special mode (like python-mode) ?

**Comment by proofit404** [comment]
The reason why `pyenv-mode` is a global minor mode is that its commands have global effect.  Current python interpreter changes for whole Emacs at ones. If the only issue is the key bindings then simply change it.

```lisp
(eval-after-load 'pyenv-mode
  '(progn
     (define-key pyenv-mode-map (kbd "C-c C-s") nil)
     (define-key pyenv-mode-map (kbd "C-M-s") 'pyenv-mode-set)))
```

**Comment by Superbil** [comment]
@proofit404 Thank you, I will use this script to remove that key bindings.

**Comment by proofit404** [comment]
You're welcome.
