### ISSUE TITLE
pyenv-mode is slow with internet connection

### ISSUE THREAD

**Issue by danceasarxx** [proofit404/pyenv-mode#26]
Using `Emacs 24.5.1` on Arch linux.
Whenever I add `(pyenv-mode)` to my **.emacs** or I run `M-x pyenv-mode` it takes `29-35s` to respond. Is `pyenv` making network  calls and if it is what is the reason for that.

**Comment by proofit404** [comment]
This is really strange behavior. Pyenv runs two shell commands `pyenv root` and `pyenv versions`. No network calls intended to happens.

**Comment by danceasarxx** [comment]
Did some checking using **nethogs** and it actually does not make any calls to the network. I also checked your source on my system and I realized calls to `pyenv root` and `pyenv versions` are only made by `pyenv-mode-set`, hence they have nothing to do with this problem. But even calls like
`M-x describe-function RET pyenv-mode RET` take as much time as loading it. Could you suggest a way to debug this issue?

**Comment by proofit404** [comment]
Try to use `profiler-start` and `profiler-report` commands.

**Comment by danceasarxx** [comment]
Tried that already, I couldn't find any reference to pyenv-mode.
![screenshot from 2016-07-21 19-11-02](https://cloud.githubusercontent.com/assets/4183766/17033659/be1a7ae8-4f6e-11e6-92f8-ccdf59d09642.png)

**Comment by proofit404** [comment]
I don't know either. Maybe it is some problem with arch linux package. Try to rebuild emacs from source.

**Comment by danceasarxx** [comment]
Checked it with bechmark-init.....something called `trampfs`. 
![screenshot from 2016-07-26 06-30-19](https://cloud.githubusercontent.com/assets/4183766/17127052/2374944c-52f2-11e6-8338-c578c90cee21.png)
After using some digging discovered it was a `require` to  `tramp-loaddefs` as shown in this pic(I'm sorry I don't have any crop tool)
![screenshot from dotscale_2013_solomon_hykes_why_we_built_docker mp4](https://cloud.githubusercontent.com/assets/4183766/17127182/1467bc12-52f3-11e6-85ae-be4b02e069e1.png)
Will move this issue to pythonic then.
